# -*- coding: utf-8 -*-
"""despliegue_clasificacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iBgvZA5fO7_qsRAhJIp-UMA2XSGSu_je

# Despliegue

- Cargamos el modelo
- Cargamos los datos
- Preparamos los datos: normalizar, dummies
- Aplicamos el modelo para la predicción
"""

# Cargamos librerías principales
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Cargamos el modelo
import pickle
filename = 'modelo-cla.pkl'
modelo, label_encoder, variables, min_max_scaler = pickle.load(open(filename, 'rb'))

# Interfaz gráfica

#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.title('Predicción de fuga de clientes (Churn) en una compañía telefónica')

tenure = st.slider('Antigüedad (en meses)', min_value=0, max_value=72, step=1)
MonthlyCharges = st.slider('Pago Mensual', min_value=18.25, max_value=118.75, step=0.25)
SeniorCitizen = st.selectbox('Adulto Mayor', ['Yes', 'No'])
Partner = st.selectbox('Partner', ['Yes', 'No'])
InternetService = st.selectbox('Servicio de Internet', ['DSL', 'Fiber optic', 'No'])
Contract = st.selectbox('Contrato', ['Month-to-month', 'One year', 'Two year'])
PaymentMethod = st.selectbox('Método de Pago', ['Electronic check', 'Mailed check', 'Bank transfer (automatic)', 'Credit card (automatic)'])
Dependents = st.selectbox('Dependientes', ['Yes', 'No'])
OnlineSecurity = st.selectbox('Seguridad Online', ['No', 'Yes'])
OnlineBackup = st.selectbox('Respaldo Online', ['No', 'Yes'])
DeviceProtection = st.selectbox('Protección de Dispositivos', ['No', 'Yes'])
TechSupport = st.selectbox('Soporte Técnico', ['No', 'Yes'])
StreamingTV = st.selectbox('Televisión', ['No', 'Yes',])
StreamingMovies = st.selectbox('Plataformas Streaming', ['No', 'Yes'])
PaperlessBilling = st.selectbox('Factura Digital', ['No', 'Yes'])


#Dataframe
datos = [[tenure, MonthlyCharges, SeniorCitizen, Partner, InternetService, Contract,
          PaymentMethod, Dependents, OnlineSecurity, OnlineBackup, DeviceProtection,
          TechSupport, StreamingTV, StreamingMovies, PaperlessBilling]]
data = pd.DataFrame(datos, columns=['tenure', 'MonthlyCharges', 'SeniorCitizen', 'Partner', 'InternetService', 'Contract',
          'PaymentMethod', 'Dependents', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
          'TechSupport', 'StreamingTV', 'StreamingMovies', 'PaperlessBilling']) #Dataframe con los mismos nombres de variables

#Dummies para las variables
data = pd.get_dummies(data, columns=['InternetService', 'Contract', 'PaymentMethod'], drop_first=False, dtype=int)
data = pd.get_dummies(data, columns=['SeniorCitizen','Partner','Dependents','OnlineSecurity',
                                     'OnlineBackup','DeviceProtection','TechSupport',
                                     'StreamingTV','StreamingMovies','PaperlessBilling'],
                       drop_first=True, dtype=int)

# Alinear columnas con las que espera el modelo
data = data.reindex(columns=variables, fill_value=0)

# Se normalizan tenure y MonthlyCharges debido a que el modelo Voting hard contiene un modelo de red neuronal
data[['tenure', 'MonthlyCharges']] = min_max_scaler.transform(data[['tenure', 'MonthlyCharges']])

"""# **Predicción**"""

# Botón y predicción
if st.button('Predecir'):
    pred = modelo.predict(data)[0]
    pred_label = label_encoder.inverse_transform([pred])[0]
    st.subheader(f'Churn: {pred_label}')
    st.warning("El modelo tiene una precisión del 81%")